plugins {
    id 'com.android.application'

    id 'kotlin-android'
    id 'kotlin-kapt'
}

android {
    compileSdkVersion COMPILE_SDK_VERSION as int

    namespace 'jp.co.cyberagent.android.gpuimage.sample'

    defaultConfig {
        minSdkVersion MIN_SDK_VERSION as int
        targetSdkVersion TARGET_SDK_VERSION as int

        versionCode = VERSION_CODE as int
        versionName = VERSION_NAME
    }

    compileOptions.with {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    buildTypes {
        debug {
            debuggable true
        }

        release {
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    kotlinOptions {
        jvmTarget = '17'
    }
}
repositories {
//     maven { url = "https://oss.sonatype.org/content/repositories/snapshots"}
}

dependencies {
    implementation project(':library')

    implementation 'androidx.appcompat:appcompat:1.7.1'
}